# Generated by Django 3.1.3 on 2020-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('banji_text', models.CharField(max_length=200)),
                ('zhuanye_text', models.CharField(max_length=200)),
                ('xueke_text', models.CharField(max_length=200)),
                ('fenshu_text', models.IntegerField()),
            ],
        ),
    ]
